apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-portfolio.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-portfolio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-portfolio.name" . }}
    spec:
      containers:
        - name: portfolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
           - containerPort: 3000
