apiVersion: v1
kind: service
metadata:
  name: {{ include "devops-portfolio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - port: 3000
   - targetPort: 3000
   - nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    app: {{ include "devops-portfolio.name" . }}