apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-portfolio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devops-portfolio.name" . }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort | default nil }}
  